import React, { useState } from 'react';
import { GripVertical } from 'lucide-react';

export const BeforeAfterSlider: React.FC = () => {
  const [sliderPosition, setSliderPosition] = useState(50);

  const handleDrag = (e: React.ChangeEvent<HTMLInputElement>) => {
    setSliderPosition(Number(e.target.value));
  };

  return (
    <div className="relative w-full max-w-4xl mx-auto aspect-video rounded-xl overflow-hidden border border-gray-200 dark:border-zinc-800 shadow-2xl group select-none bg-gray-100 dark:bg-zinc-900">
      
      {/* "Before" Image */}
      <div className="absolute inset-0 w-full h-full flex items-center justify-center bg-white dark:bg-zinc-900">
        <div className="text-center p-8 opacity-40 grayscale">
            {/* Wireframe representation */}
            <div className="border-2 border-dashed border-gray-400 dark:border-gray-600 w-64 h-40 mx-auto mb-4 flex flex-col items-center justify-center gap-2">
                <div className="w-12 h-12 rounded-full bg-gray-300 dark:bg-zinc-800"></div>
                <div className="w-32 h-4 bg-gray-300 dark:bg-zinc-800 rounded"></div>
            </div>
            <h3 className="text-2xl font-bold text-gray-400 dark:text-zinc-500 mb-2">Boring & Unnoticed</h3>
            <p className="text-gray-400 dark:text-zinc-600 font-medium">0.8% CTR • No Views</p>
        </div>
      </div>

      {/* "After" Image */}
      <div 
        className="absolute inset-0 w-full h-full overflow-hidden"
        style={{ 
            clipPath: `polygon(0 0, ${sliderPosition}% 0, ${sliderPosition}% 100%, 0 100%)`,
        }}
      >
        <img 
            src="https://picsum.photos/seed/viral12/1280/720" 
            className="w-full h-full object-cover filter contrast-125 saturate-150"
            alt="Viral Result"
        />
        <div className="absolute top-4 right-4 bg-red-600 text-white px-3 py-1 rounded-md font-bold text-xs shadow-lg transform rotate-2">
            VIRAL MODE ON
        </div>
        <div className="absolute bottom-4 left-4 bg-black/70 backdrop-blur-md text-white px-4 py-2 rounded-lg font-bold text-sm">
           Generated by Gemini 3
        </div>
      </div>

      {/* Slider Handle */}
      <div 
        className="absolute inset-y-0 w-1 bg-white cursor-ew-resize"
        style={{ left: `${sliderPosition}%` }}
      >
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-10 h-10 bg-white rounded-full shadow-lg flex items-center justify-center text-yt-red border-2 border-gray-100">
            <GripVertical size={20} />
        </div>
      </div>

      <input
        type="range"
        min="0"
        max="100"
        value={sliderPosition}
        onChange={handleDrag}
        className="absolute inset-0 w-full h-full opacity-0 cursor-ew-resize z-10"
      />
    </div>
  );
};