import React, { useState, useRef, useEffect } from "react";
import {
  Send,
  Sparkles,
  Bot,
  Download,
  Share2,
  ThumbsUp,
  ThumbsDown,
  Edit2,
  ShieldCheck,
  Zap,
  Check,
  ExternalLink,
} from "lucide-react";
import { Button } from "../ui/Button";
import { motion, AnimatePresence } from "framer-motion";
import { clsx, type ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";

function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

// --- Types ---
interface Message {
  id: string;
  role: "user" | "assistant";
  content: string;
  imageUrl?: string;
  timestamp: Date;
}

interface ChatFeedProps {
  user: any;
  topic: string;
  setTopic: (val: string) => void;
  generationTrigger: number;
  onGenerationComplete: () => void;
}

export const ChatFeed: React.FC<ChatFeedProps> = ({
  user,
  topic,
  setTopic,
  generationTrigger,
  onGenerationComplete,
}) => {
  // State
  const [messages, setMessages] = useState<Message[]>([]);
  const [input, setInput] = useState("");
  const [isChatGenerating, setIsChatGenerating] = useState(false);
  const [hasStarted, setHasStarted] = useState(false);
  const [feedbackMap, setFeedbackMap] = useState<Record<string, "up" | "down">>(
    {}
  );

  const scrollRef = useRef<HTMLDivElement>(null);
  const inputRef = useRef<HTMLInputElement>(null);

  // Test Mode Counter
  const demoCounter = useRef(0);

  // Auto-scroll
  useEffect(() => {
    if (scrollRef.current) {
      scrollRef.current.scrollTo({
        top: scrollRef.current.scrollHeight,
        behavior: "smooth",
      });
    }
  }, [messages, isChatGenerating]);

  // Handle Sidebar Trigger
  useEffect(() => {
    if (generationTrigger > 0 && topic) {
      handleGenerate(topic);
    }
  }, [generationTrigger]);

  // --- ACTIONS ---

  const handleDownload = async (imageUrl: string, filename: string) => {
    try {
      const response = await fetch(imageUrl);
      const blob = await response.blob();
      const url = window.URL.createObjectURL(blob);
      const link = document.createElement("a");
      link.href = url;
      link.download = `bananaviral-${filename}.jpg`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      window.URL.revokeObjectURL(url);
    } catch (error) {
      console.error("Download failed", error);
      // Fallback
      window.open(imageUrl, "_blank");
    }
  };

  const handleShare = async (imageUrl: string) => {
    if (navigator.share) {
      try {
        await navigator.share({
          title: "BananaViral Result",
          text: "Check out this thumbnail generated by BananaViral!",
          url: imageUrl,
        });
      } catch (err) {
        console.log("Share canceled");
      }
    } else {
      await navigator.clipboard.writeText(imageUrl);
      alert("Image URL copied to clipboard!");
    }
  };

  const handleFeedback = (id: string, type: "up" | "down") => {
    setFeedbackMap(
      (prev) =>
        ({
          ...prev,
          [id]: prev[id] === type ? undefined : type, // Toggle
        } as any)
    );
  };

  const handleRefineClick = () => {
    setInput("Make the text pop more and increase contrast...");
    inputRef.current?.focus();
  };

  // --- GENERATION LOGIC ---
  const handleGenerate = async (promptText: string) => {
    setHasStarted(true);
    setIsChatGenerating(true);

    const userMsg: Message = {
      id: Date.now().toString(),
      role: "user",
      content: promptText,
      timestamp: new Date(),
    };
    setMessages((prev) => [...prev, userMsg]);
    setInput("");

    // Simulate AI Delay
    setTimeout(() => {
      let aiContent = "";
      let aiImage = "";

      if (demoCounter.current === 0) {
        aiContent =
          "I've generated a high-CTR YouTube thumbnail based on your concept. Note the high contrast text for better readability on mobile.";
        aiImage = "/youtube.jpeg";
      } else {
        aiContent =
          "Here is the vertical variation optimized for TikTok (9:16). I've centered the subject to avoid the UI overlays.";
        aiImage = "/tiktok.jpeg";
      }

      demoCounter.current = (demoCounter.current + 1) % 2;

      const aiMsg: Message = {
        id: (Date.now() + 1).toString(),
        role: "assistant",
        content: aiContent,
        imageUrl: aiImage,
        timestamp: new Date(),
      };

      setMessages((prev) => [...prev, aiMsg]);
      setIsChatGenerating(false);
      onGenerationComplete();
    }, 2500);
  };

  const handleInputSend = () => {
    if (!input.trim()) return;
    handleGenerate(input);
  };

  return (
    <div className="flex flex-col h-full w-full relative bg-gray-50/30 dark:bg-[#09090b]">
      {/* VIEW 1: WELCOME STATE */}
      {!hasStarted && (
        <div className="flex-1 flex flex-col items-center justify-center p-8 transition-all duration-700">
          <div className="max-w-md w-full flex flex-col items-center text-center space-y-6">
            <div className="relative w-24 h-24 flex items-center justify-center">
              {isChatGenerating && (
                <motion.div
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1, rotate: 360 }}
                  transition={{ duration: 2, repeat: Infinity, ease: "linear" }}
                  className="absolute inset-0 rounded-full border-[3px] border-transparent border-t-brand-yellow border-r-brand-yellow/50"
                />
              )}
              <img
                src="/logo.png"
                alt="BananaViral"
                className={cn(
                  "w-16 h-16 rounded-2xl object-cover transition-all duration-700 ease-in-out z-10",
                  isChatGenerating
                    ? "grayscale-0 scale-110 shadow-[0_0_30px_rgba(250,204,21,0.4)]"
                    : "grayscale opacity-40 shadow-none scale-100"
                )}
              />
            </div>
            <div className="space-y-2">
              <h1
                className={cn(
                  "text-2xl font-bold tracking-tight transition-colors duration-500",
                  isChatGenerating
                    ? "text-gray-900 dark:text-white"
                    : "text-gray-400 dark:text-zinc-600"
                )}
              >
                BananaViral Studio
              </h1>
              <p
                className={cn(
                  "text-sm max-w-xs mx-auto transition-colors duration-500",
                  isChatGenerating
                    ? "text-gray-600 dark:text-gray-300"
                    : "text-gray-400 dark:text-zinc-600"
                )}
              >
                {isChatGenerating
                  ? "Analyzing your prompt and generating visuals..."
                  : "Ready. Use the sidebar to start a new session."}
              </p>
            </div>
          </div>
        </div>
      )}

      {/* VIEW 2: CHAT INTERFACE */}
      {hasStarted && (
        <>
          <div
            ref={scrollRef}
            className="flex-1 overflow-y-auto custom-scrollbar p-4 md:px-0 py-6 scroll-smooth"
          >
            <div className="max-w-3xl mx-auto space-y-8 px-4 md:px-6 pb-8">
              <div className="flex items-center justify-center gap-2 text-[10px] text-gray-300 dark:text-zinc-700 uppercase tracking-widest font-bold mb-8 opacity-50 select-none">
                <ShieldCheck size={12} /> Secure Generation Environment
              </div>

              {messages.map((msg) => (
                <motion.div
                  initial={{ opacity: 0, y: 15 }}
                  animate={{ opacity: 1, y: 0 }}
                  key={msg.id}
                  className={cn(
                    "flex gap-4",
                    msg.role === "user" ? "justify-end" : "justify-start"
                  )}
                >
                  {msg.role === "assistant" && (
                    <div className="w-8 h-8 rounded-lg bg-brand-yellow flex items-center justify-center shrink-0 shadow-sm mt-1">
                      <img
                        src="/logo.png"
                        className="w-full h-full object-cover rounded-lg opacity-90 mix-blend-multiply"
                        alt="Bot"
                      />
                    </div>
                  )}

                  <div
                    className={cn(
                      "flex flex-col gap-2 max-w-[85%] md:max-w-[75%]",
                      msg.role === "user" ? "items-end" : "items-start"
                    )}
                  >
                    {msg.role === "user" ? (
                      <div className="bg-white dark:bg-zinc-800 border border-gray-100 dark:border-zinc-700 px-5 py-3 rounded-2xl rounded-tr-sm text-gray-800 dark:text-gray-100 text-sm font-medium shadow-sm">
                        {msg.content}
                      </div>
                    ) : (
                      <div className="px-1 text-sm text-gray-600 dark:text-gray-300 font-medium mb-1">
                        {msg.content}
                      </div>
                    )}

                    {/* Result Image Card - RESIZED AND WIRED UP */}
                    {msg.role === "assistant" && msg.imageUrl && (
                      <div className="w-full bg-white dark:bg-zinc-900 rounded-2xl p-1 border border-gray-200 dark:border-zinc-800 shadow-xl overflow-hidden group max-w-md">
                        <div className="relative overflow-hidden rounded-xl bg-gray-100 dark:bg-black group-hover:shadow-inner transition-all">
                          {/* Image with MAX HEIGHT to prevent "too big" look */}
                          <img
                            src={msg.imageUrl}
                            className="w-full max-h-[500px] object-contain mx-auto transition-transform duration-700 group-hover:scale-105"
                            alt="Result"
                          />

                          {/* Overlay Actions */}
                          <div className="absolute inset-0 bg-black/40 opacity-0 group-hover:opacity-100 transition-opacity duration-200 flex items-center justify-center backdrop-blur-[2px]">
                            <div className="flex gap-2 transform translate-y-4 group-hover:translate-y-0 transition-transform duration-300">
                              <Button
                                onClick={() =>
                                  handleDownload(msg.imageUrl!, msg.id)
                                }
                                variant="viral"
                                size="sm"
                                className="h-9 px-4 text-xs shadow-lg"
                              >
                                <Download size={14} className="mr-2" /> Download
                              </Button>
                              <Button
                                onClick={() => handleShare(msg.imageUrl!)}
                                variant="outline"
                                size="sm"
                                className="h-9 px-4 text-xs bg-white text-black border-none hover:bg-gray-100 shadow-lg"
                              >
                                <Share2 size={14} className="mr-2" /> Share
                              </Button>
                            </div>
                          </div>
                        </div>

                        {/* Refinement Options */}
                        <div className="p-3 flex items-center justify-between border-t border-gray-100 dark:border-zinc-800 bg-gray-50/50 dark:bg-zinc-900/50">
                          <div className="flex gap-1">
                            <button
                              onClick={() => handleFeedback(msg.id, "up")}
                              className={cn(
                                "p-1.5 rounded-md transition-colors",
                                feedbackMap[msg.id] === "up"
                                  ? "text-green-600 bg-green-50"
                                  : "text-gray-400 hover:text-green-500 hover:bg-green-500/10"
                              )}
                            >
                              <ThumbsUp size={14} />
                            </button>
                            <button
                              onClick={() => handleFeedback(msg.id, "down")}
                              className={cn(
                                "p-1.5 rounded-md transition-colors",
                                feedbackMap[msg.id] === "down"
                                  ? "text-red-600 bg-red-50"
                                  : "text-gray-400 hover:text-red-500 hover:bg-red-500/10"
                              )}
                            >
                              <ThumbsDown size={14} />
                            </button>
                          </div>
                          <div className="flex gap-2">
                            <button
                              onClick={handleRefineClick}
                              className="text-[10px] font-bold text-gray-500 hover:text-brand-yellow flex items-center gap-1 px-2 py-1 rounded hover:bg-brand-yellow/10 transition-colors"
                            >
                              <Edit2 size={10} /> Refine Result
                            </button>
                          </div>
                        </div>
                      </div>
                    )}
                  </div>
                </motion.div>
              ))}

              {isChatGenerating && (
                <motion.div
                  initial={{ opacity: 0, scale: 0.95 }}
                  animate={{ opacity: 1, scale: 1 }}
                  className="flex gap-4"
                >
                  <div className="w-8 h-8 rounded-lg bg-brand-yellow/10 border border-brand-yellow/20 flex items-center justify-center shrink-0">
                    <Zap
                      size={14}
                      className="text-brand-yellow fill-brand-yellow animate-pulse"
                    />
                  </div>
                  <div className="bg-white dark:bg-zinc-900 px-5 py-4 rounded-2xl rounded-tl-sm shadow-sm border border-gray-100 dark:border-zinc-800 flex items-center gap-3">
                    <div className="flex space-x-1">
                      <motion.div
                        animate={{ scale: [1, 1.2, 1] }}
                        transition={{ repeat: Infinity, duration: 1 }}
                        className="w-1.5 h-1.5 bg-brand-yellow rounded-full"
                      />
                      <motion.div
                        animate={{ scale: [1, 1.2, 1] }}
                        transition={{
                          repeat: Infinity,
                          duration: 1,
                          delay: 0.2,
                        }}
                        className="w-1.5 h-1.5 bg-brand-yellow rounded-full"
                      />
                      <motion.div
                        animate={{ scale: [1, 1.2, 1] }}
                        transition={{
                          repeat: Infinity,
                          duration: 1,
                          delay: 0.4,
                        }}
                        className="w-1.5 h-1.5 bg-brand-yellow rounded-full"
                      />
                    </div>
                    <span className="text-xs font-bold text-gray-500 dark:text-zinc-500 uppercase tracking-wide">
                      Generating...
                    </span>
                  </div>
                </motion.div>
              )}
            </div>
          </div>

          {/* STICKY INPUT */}
          <div className="p-5 bg-white/80 dark:bg-[#09090b]/90 backdrop-blur-xl border-t border-gray-200/50 dark:border-white/5 z-20">
            <div className="max-w-3xl mx-auto relative group">
              <div className="absolute inset-0 bg-gradient-to-r from-brand-yellow/20 to-purple-500/20 rounded-full blur-xl opacity-0 group-hover:opacity-100 transition-opacity duration-500 pointer-events-none" />

              <div className="relative flex items-center bg-white dark:bg-[#121214] border border-gray-200 dark:border-zinc-700 rounded-full shadow-lg overflow-hidden transition-all focus-within:ring-2 focus-within:ring-brand-yellow/50 focus-within:border-brand-yellow">
                <div className="pl-4 text-gray-400">
                  <Sparkles size={18} />
                </div>
                <input
                  ref={inputRef}
                  value={input}
                  onChange={(e) => setInput(e.target.value)}
                  onKeyDown={(e) => e.key === "Enter" && handleInputSend()}
                  disabled={isChatGenerating}
                  placeholder="Refine this result... (e.g. 'Make the expression more surprised')"
                  className="w-full h-12 pl-3 pr-14 bg-transparent border-none focus:ring-0 text-sm font-medium text-gray-900 dark:text-white placeholder:text-gray-400"
                />
                <button
                  onClick={handleInputSend}
                  disabled={!input.trim() || isChatGenerating}
                  className="absolute right-1.5 top-1.5 w-9 h-9 flex items-center justify-center bg-brand-yellow hover:bg-yellow-400 text-black rounded-full transition-all disabled:opacity-50 disabled:bg-gray-200 disabled:text-gray-400"
                >
                  <Send
                    size={16}
                    className={input.trim() ? "-rotate-45 mr-0.5 mt-0.5" : ""}
                  />
                </button>
              </div>

              <div className="text-center mt-2">
                <p className="text-[10px] text-gray-400 dark:text-zinc-600 font-medium">
                  BananaViral AI can make mistakes. Use refinements to perfect
                  your thumbnail.
                </p>
              </div>
            </div>
          </div>
        </>
      )}
    </div>
  );
};
